---

- name: PHP_FPM | Create sockets directory
  file:
    path: /var/run/php-fpm/
    state: directory
    owner: "{{ php_fpm_owner }}"
    group: "{{ php_fpm_group }}"
    mode: "g+rw"

- name: PHP_FPM | Disable default pool
  file:
    path: "{{ php_fpm_path }}/fpm/pool.d/{{ item }}"
    state: absent
  with_items: "{{ php_fpm_pools_disable }}"
  notify: restart php-fpm

- name: PHP_FPM | Copy php-fpm pools configurations
  template:
    src: "{{ item.value.src|default(php_fpm_template) }}"
    dest: "{{ php_fpm_path }}/fpm/pool.d/{{ item.value.dest|default(item.key ~ '.conf') }}"
    owner: "{{ php_fpm_owner }}"
    group: "{{ php_fpm_group }}"
  with_dict: "{{ php_fpm_pools | default({}) }}" 
  notify: restart php-fpm
